import java.util.ArrayList;
import java.util.List;

/**
 * https://projecteuler.net
 * 
 * Problem 2:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * Find the sum of all the even-valued terms in the sequence which do not exceed four million.
 *
 * F1 = 1,
 * F2 = 1,
 * Fn = F{n-1} + F{n-2}
 * 
 * 1,1,2,3,5,8,13,21,34,55,89,144,...
 *
 * @author michelesartini
 *
 */

public class Main {
	static int sumLimit = 4000000;
	
	public static void main(String[] args) {
		fibonacciEvenTermsSumBruteForce(sumLimit);
		fibonacciEvenTermsSum(sumLimit);
	}
	
	public static void fibonacciEvenTermsSumBruteForce(int limit) {
		int sum = 0;
		List<Integer> fib = new ArrayList<Integer>();
		fib.add(0, 1);
		fib.add(1, 1);
		
		for (int i = 2; sum < limit; i++) {
			fib.add(i, fib.get(i-1) + fib.get(i-2));
			if ((fib.get(i) % 2 == 0)) {
				sum += fib.get(i);
			}
		}
		System.out.println("Sum: " + sum);
	}
	
	/**
	 * Smart sum.
	 * 
	 * F{n} = F{n-1} + f{n-2} 
	 * where: 
	 * F{n-1} = F{n-2} + F{n-3}
	 * F{n-2} = F{n-3} + F{n-4}
	 * F{n-3} = F{n-4} + F{n-5}
	 * F{n-4} = F{n-5} + F{n-6}
	 * therefore:
	 * F{n} = F{n-1} + f{n-2} = F{n-2} + F{n-3} + F{n-3} + F{n-4} = F{n-3} + F{n-4} + F{n-3} + F{n-3} + F{n-4} =
	 * 3F{n-3} + 2F{n-4} = F{n-3} + F{n-3} + F{n-3} + F{n-4} + F{n-4} =
	 * F{n-3} + F{n-3} + F{n-3} + F{n-4} + F{n-5} + F{n-6} =
	 * where F{n-4} + F{n-5} = F{n-3}
	 * therefore:
	 * F{n-3} + F{n-3} + F{n-3} + F{n-3} + F{n-6} = 4F{n-3} + F{n-6}
	 * 
	 * 
	 * According to this:
	 * 1,1,2,3,5,8,13,21,34,55,89,144,...
	 * 
	 * fn6 = 2
	 * fn3 = 0
	 * 4 * fn6 + fn3 = 8
	 * 
	 * fn6 = 8
	 * fn3 = 2
	 * 4 * fn6 + fn3 = 34
	 * 
	 * fn6 = 34
	 * fn3 = 8
	 * 4 * fn6 + fn3 = 144
	 * 
	 */
	public static void fibonacciEvenTermsSum(int limit) {
		int sum = 0;
		int fn = 2;
		int fn6 = 2;
		int fn3 = 0;
		
		while (sum < limit) {
			sum += fn;
			
			fn = 4 * fn6 + fn3;
			fn3 = fn6;
			fn6 = fn;
		}
		System.out.println("Sum: " + sum);
	}
}
